###Project 1 Web Scraping with Pandas

In [1]:
import pandas as pd
import numpy as np

In [9]:
#reading 1 csv file from the website (https://football-data.co.uk/data.php)
df_premier2026 = pd.read_csv('https://football-data.co.uk/mmz4281/2526/E0.csv')
df_premier2026.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [10]:
#Rename columns
df_premier2026.rename(columns = {'FTHG': 'home_goals', 'FTAG':'away_goals'}, inplace=True)
df_premier2026

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,24/05/2026,16:00,Man City,Aston Villa,1,2,A,1,0,...,1.83,2.03,NaN,NaN,1.83,2.05,1.78,1.98,1.90,2.09
376,E0,24/05/2026,16:00,Nott'm Forest,Bournemouth,1,1,D,1,0,...,1.90,1.95,NaN,NaN,1.90,1.95,1.81,1.91,1.94,2.04
377,E0,24/05/2026,16:00,Sunderland,Chelsea,2,1,H,1,0,...,1.80,2.05,NaN,NaN,1.80,2.05,1.75,1.99,1.87,2.12
378,E0,24/05/2026,16:00,Tottenham,Everton,1,0,H,1,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.85,1.87,1.96,2.03
379,E0,24/05/2026,16:00,West Ham,Leeds,3,0,H,0,0,...,1.93,1.93,NaN,NaN,1.93,1.93,1.86,1.89,1.97,2.01

###Read .csv from Multiple URLs with Pandas

#link: root + season + league
#link structure
'https://football-data.co.uk/mmz4281/' + '2526' + '/' + 'E0' + ''.csv'

In [11]:
#Create a root variable
root = 'https://football-data.co.uk/mmz4281/'

In [12]:
#Creating list of leagues
leagues = ['E0', 'E1', 'E2', 'E3', 'EC']

In [18]:
#looping through leagues, read multiple csv and append it into a list
frames = []

for league in leagues:
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + league + '.csv', encoding='unicode_escape')
        df.insert(1, 'season', season)
        frames.append(df)

In [15]:
#length of frames
len(frames)

5

In [19]:
#show 1st, 2nd and 3rd element
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E2,20,12/09/2020,15:00,Accrington,Peterboro,2,0,H,1,...,2.03,0.25,2.02,1.83,2.08,1.83,2.09,1.87,2.02,1.81
1,E2,20,12/09/2020,15:00,Crewe,Charlton,0,2,A,0,...,1.88,0.00,1.95,1.90,1.96,1.94,2.00,1.95,1.94,1.89
2,E2,20,12/09/2020,15:00,Doncaster,Milton Keynes Dons,1,1,D,0,...,1.69,-0.25,1.80,2.05,1.81,2.12,1.85,2.12,1.80,2.05
3,E2,20,12/09/2020,15:00,Fleetwood Town,Burton,2,1,H,1,...,1.85,-0.50,1.98,1.88,1.95,1.95,2.06,1.95,1.97,1.86
4,E2,20,12/09/2020,15:00,Gillingham,Hull,0,2,A,0,...,1.86,0.00,1.85,2.00,1.91,2.00,1.93,2.06,1.85,1.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E2,20,09/05/2021,12:00,Milton Keynes Dons,Rochdale,0,3,A,0,...,2.56,-0.75,1.88,1.98,1.88,2.01,1.96,2.04,1.87,1.97
548,E2,20,09/05/2021,12:00,Oxford,Burton,4,0,H,2,...,2.38,-1.00,1.85,2.00,1.88,2.02,2.11,2.06,1.88,1.95
549,E2,20,09/05/2021,12:00,Portsmouth,Accrington,0,1,A,0,...,2.21,-1.00,1.95,1.90,1.99,1.90,2.07,1.94,1.95,1.88
550,E2,20,09/05/2021,12:00,Sunderland,Northampton,1,1,D,0,...,2.13,-1.25,1.98,1.88,2.02,1.88,2.10,1.91,2.01,1.83
551,E2,20,09/05/2021,12:00,Wigan,Swindon,3,4,A,1,...,2.28,-0.75,1.93,1.93,2.00,1.88,2.01,1.97,1.93,1.90

###Organize all the data in a dictionary

In [23]:
#Create a dictionary with original name of league as key
dict_countries = {
    'Spanish la liga': 'SP1',
    'Spanish Segunda Division': 'SP2',
    'German Bundesliga': 'D1',
    'English Premier League': 'E0',
    'English League 1': 'E1',
    'English League 2': 'E2'
}

In [20]:
#get a dictionary element

In [24]:
dict_historical_data = {}
#looping through key elements

for league in dict_countries:
    frames = []
    for season in range(15, 21):
        df = pd.read_csv(root + str(season) + str(season+1) + '/' + dict_countries[league] + '.csv', encoding='unicode_escape')
        df.insert(1, 'season', season)
        frames.append(df)
    df_concat = pd.concat(frames)
    dict_historical_data[league] = df_concat

In [26]:
#show dataframe inside dict_historical_data
dict_historical_data.keys()

dict_keys(['Spanish la liga', 'Spanish Segunda Division', 'German Bundesliga', 'English Premier League', 'English League 1', 'English League 2'])

In [27]:
dict_historical_data['English Premier League']

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,20,23/05/2021,Liverpool,Crystal Palace,2,0,H,1,0,...,3.49,-2.25,1.86,2.04,1.88,2.03,1.98,2.14,1.88,2.00
376,E0,20,23/05/2021,Man City,Everton,5,0,H,2,0,...,2.77,-1.75,2.01,1.89,1.99,1.89,2.20,2.00,2.03,1.85
377,E0,20,23/05/2021,Sheffield United,Burnley,1,0,H,1,0,...,2.05,0.00,2.04,1.86,2.05,1.86,2.17,1.90,2.03,1.84
378,E0,20,23/05/2021,West Ham,Southampton,3,0,H,2,0,...,2.14,-0.75,2.00,1.90,2.02,1.91,2.06,2.01,1.99,1.89
379,E0,20,23/05/2021,Wolves,Man United,1,2,A,1,2,...,1.62,-0.25,2.04,1.86,2.10,1.84,2.10,1.94,2.00,1.88