###Introduction to Pandas

In [169]:
import pandas as pd
import numpy as np

In [170]:
#Creating an array
data = np.array([[1,4], [2,5], [3,6]])
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [171]:
#Creating a dataframe
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns = ['col1', 'col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [172]:
data = [[1,4], [2,5], [3,6]]
df = pd.DataFrame(data, index=['row1', 'row2', 'row3'], columns = ['col1', 'col2'])
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

In [173]:
#Creating a DataFrame from a dictionary
states = ['California', 'Texas', 'Florida', 'New York']
population = [39613493, 29730311, 21944577, 19299981]

In [174]:
dict_states = {'states':states, 'Population':population}
dict_states

{'states': ['California', 'Texas', 'Florida', 'New York'],
 'Population': [39613493, 29730311, 21944577, 19299981]}

In [175]:
df_population = pd.DataFrame(dict_states)
df_population

       states  Population
0  California    39613493
1       Texas    29730311
2     Florida    21944577
3    New York    19299981

In [176]:
#Creating a DataFrame from a csv file
df_exams = pd.read_csv('StudentsPerformance.csv')
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [177]:
#Show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [178]:
#Show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [179]:
#Show last n rows in a dataframe
df_exams.tail(7)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [180]:
#Getting access to the shape attribute
df_exams.shape

(1000, 8)

In [181]:
pd.set_option('display.max_rows', 10)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

###Attributes, Methods and Functions

-> Attributes: A value associated with an object (referenced by name using dotted expressions). 
    Ex: df.columns

-> Function: A group of related statements that performs a specific task.
    Ex: python built-in functions: max(); min(); len()

-> Methods: A function which is defined inside a class body.
    Ex: df.head()

####Attributes

In [182]:
#Getting access to the shape attribute
df_exams.shape

(1000, 8)

In [183]:
#Getting access to the index attribute
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [184]:
#Getting access to columns attribute
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [185]:
#Data types of each column
df_exams.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

####Methods

In [186]:
#Showing the first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [187]:
#Showing the info ofthe dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [188]:
#Describing basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

####Functions

In [189]:
#Obtaining the length of the dataframe (number of rows)
len(df_exams)

1000

In [190]:
#Obtaining the highest index of the dataframe
max(df_exams.index)

999

In [191]:
#Obtaining the lowest index of the dataframe
min(df_exams.index)

0

In [192]:
#Obtaining the data type
type(df_exams)

pandas.core.frame.DataFrame

In [193]:
#Rounding the values of the dataset
round(df_exams, 2).head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

###Selecting one column

In [194]:
#Select a column with [] (preferred way to select a column)
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [195]:
#Check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [196]:
#Series: attributes and methods
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [197]:
#Select a column with '.'
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [198]:
#Select a column with '.' (pitfalls)
#df_exams.math score -> invalid syntax por causa do espaço

In [199]:
#Select the same column using []
df_exams['math score'].head()

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

###Selecting two or more columns

In [200]:
#select 2 columns using [[]]
df_exams[['gender', 'math score']].head()

   gender  math score
0  female          72
1  female          69
2  female          90
3    male          47
4    male          76

In [201]:
#Check out the data type of the selection
type(df_exams[['gender', 'math score']].head())

pandas.core.frame.DataFrame

In [202]:
#Select 2 or more columns using [[]]
df_exams[['gender', 'math score', 'lunch']].head()

   gender  math score         lunch
0  female          72      standard
1  female          69      standard
2  female          90      standard
3    male          47  free/reduced
4    male          76      standard

In [203]:
#We can't select 2 or more columns with the '.'

Adding a new column

In [204]:
#Adding a new column with a scalar value. Adding new column to dataframe
df_exams['language score'] = 70
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70

In [205]:
#Adding a new column with an array. The dataframe has 1000 rows, so we need to create an array with 1000 elements
#Create an array of 1000 elements
language_score = np.arange(0, 1000)

In [206]:
#Adding a new column to dataframe with an array
df_exams['language score'] = language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4

In [207]:
#Create random integer numbers between 1 and 100
int_language_score = np.random.randint(1, 100, size = 1000)

In [208]:
#min value inclusive and high value exclusive
min(int_language_score)

np.int64(1)

In [209]:
#high value inclusive and high value exclusive
max(int_language_score)

np.int64(99)

In [210]:
#Adding a new column to dataframe with an array
df_exams['language score'] = int_language_score
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,87
1,female,group C,some college,standard,completed,69,90,88,11
2,female,group B,master's degree,standard,none,90,95,93,14
3,male,group A,associate's degree,free/reduced,none,47,57,44,56
4,male,group C,some college,standard,none,76,78,75,69

In [211]:
#Create random float numbers between 1 and 100
np.random.uniform(1, 100, size=100)

array([46.97705401, 46.38494589,  3.78855556, 39.40514981, 29.96098217,
       31.09583056, 23.0378128 , 69.49430807, 51.71351475, 19.72531377,
        6.90111769, 54.18141892, 53.59477356, 90.03648403, 57.97177596,
       64.05451659, 69.09503504, 38.06769101,  9.11309155, 44.62950032,
       52.49830339, 11.38632922, 60.93341983, 32.35600418, 50.18467819,
       58.01340001, 60.03378136, 81.66027138, 91.90070775, 94.44732542,
       13.81084532, 27.90535859, 12.78943789, 95.70605921, 19.9671865 ,
       76.73273997, 45.81770247,  4.06955633, 94.78188409, 55.97684703,
       59.44351053, 37.84585784, 11.83771701, 15.17971135, 94.06759757,
       91.0296916 , 33.01094877, 42.21899788, 77.30298972, 92.99126236,
       34.1378122 , 13.02130699, 66.29352058, 13.76933943, 47.09330367,
       99.73140528, 57.20819666, 23.79225076, 96.03025709, 31.03390889,
       70.99041058, 23.71021711, 61.99805988, 12.06857457, 34.49778158,
       99.81843991, 73.67031503, 12.26604593, 13.63285047, 53.1055398 ,
       42.08523525, 83.86263802, 93.34285047, 30.87253086, 57.92934219,
       86.71842734, 49.83037973, 30.51776733, 49.90920252, 34.78476357,
       44.00296173, 11.4482806 , 56.28584741, 71.09229223, 29.48980995,
       70.11577398, 15.87444761, 89.71607554, 73.72993271, 79.1109825 ,
       36.93786757, 35.43154713, 89.63381275, 66.17818303, 60.42832992,
       20.23017729, 24.14159709, 49.1004291 , 51.42152402, 68.8957782 ])

assing()

When to use assing?

    -> Add multiple columns in a single line of code
    -> When you need to overwrite the values of an existing columns (best practice)

It returns a new object (a copy) with all the original columns in addition to the new ones

In [212]:
#Create random numbers for our new score columns
score_1 = np.random.randint(1,100, size=1000)
score_2 = np.random.randint(1,100, size=1000)

In [213]:
#Create a series using the random numbers
series_1 = pd.Series(score_1, index=np.arange(0, 1000))
series_2 = pd.Series(score_2, index=np.arange(0, 1000))

In [214]:
#Using assign() to add multiple columns
df_exams = df_exams.assign(score_1= series_1,score_2 = series_2)
df_exams.head(3)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2
0,female,group B,bachelor's degree,standard,none,72,72,74,87,58,54
1,female,group C,some college,standard,completed,69,90,88,11,7,50
2,female,group B,master's degree,standard,none,90,95,93,14,68,82

isert()

Inserts a new column at a specific position or index

In [215]:
#Using index() to add a column at a specific position
df_exams.insert(1, 'test', series_1) #(número do índice, nome da coluna, valor da coluna)
df_exams.head(3)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2
0,female,58,group B,bachelor's degree,standard,none,72,72,74,87,58,54
1,female,7,group C,some college,standard,completed,69,90,88,11,7,50
2,female,68,group B,master's degree,standard,none,90,95,93,14,68,82

###Math operations

####Operations in columns

In [216]:
#Select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [217]:
#count, mean, std, max, and min of a column
df_exams['math score'].count()

np.int64(1000)

In [218]:
df_exams['math score'].mean()

np.float64(66.089)

In [219]:
df_exams['math score'].std()

15.163080096009468

In [220]:
df_exams['math score'].max()

100

In [221]:
df_exams['math score'].min()

0

In [222]:
#easier calculation with .describbe()
df_exams.describe()

,test,math score,reading score,writing score,language score,score_1,score_2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,49.130000,66.08900,69.169000,68.054000,50.625000,49.130000,50.370000
std,28.692723,15.16308,14.600192,15.195657,27.776896,28.692723,27.860569
min,1.000000,0.00000,17.000000,10.000000,1.000000,1.000000,1.000000
25%,25.000000,57.00000,59.000000,57.750000,28.000000,25.000000,28.000000
50%,48.000000,66.00000,70.000000,69.000000,51.000000,48.000000,50.000000
75%,74.000000,77.00000,79.000000,79.000000,74.000000,74.000000,74.000000
max,99.000000,100.00000,100.000000,100.000000,99.000000,99.000000,99.000000

####Operation in rows

In [223]:
#Calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [224]:
#Calculating the average score and assinging the result to a new column
df_exams['average'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3
df_exams.head(3).round(2)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
0,female,58,group B,bachelor's degree,standard,none,72,72,74,87,58,54,72.67
1,female,7,group C,some college,standard,completed,69,90,88,11,7,50,82.33
2,female,68,group B,master's degree,standard,none,90,95,93,14,68,82,92.67

###Value counts

In [225]:
#Counting gender elements

#len function
len(df_exams['gender'])

#.count() method
df_exams['gender'].count()

np.int64(1000)

In [226]:
#Counting gender elements by category
df_exams['gender'].value_counts()

gender
female    518
male      482
Name: count, dtype: int64

In [227]:
#return the relative frequencyy (divide all values by the sum of values)
df_exams['gender'].value_counts(normalize=True)

gender
female    0.518
male      0.482
Name: proportion, dtype: float64

In [228]:
#Counting 'parental level of education' elements by category
df_exams['parental level of education'].value_counts()

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

In [229]:
#return the relative frequencyy and round to 2 decimals
df_exams['parental level of education'].value_counts(normalize=True).round(2)

parental level of education
some college          0.23
associate's degree    0.22
high school           0.20
some high school      0.18
bachelor's degree     0.12
master's degree       0.06
Name: proportion, dtype: float64

###Sort a dataframe

In [230]:
#Sort by one column
df_exams.sort_values(by='math score')

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
59,female,27,group C,some high school,free/reduced,none,0,17,10,30,27,46,9.000000
980,female,49,group B,high school,free/reduced,none,8,24,23,12,49,73,18.333333
17,female,7,group B,some high school,free/reduced,none,18,32,28,43,7,19,26.000000
787,female,76,group B,some college,standard,none,19,38,32,29,76,89,29.666667
145,female,53,group C,some college,free/reduced,none,22,39,33,47,53,28,31.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
625,male,7,group D,some college,standard,completed,100,97,99,78,7,57,98.666667
623,male,3,group A,some college,standard,completed,100,96,86,66,3,23,94.000000
451,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
962,female,37,group E,associate's degree,standard,none,100,100,100,99,37,97,100.000000
149,male,14,group E,associate's degree,free/reduced,completed,100,100,93,51,14,92,97.666667

In [231]:
#Sort descending by on column
df_exams.sort_values('math score', ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
962,female,37,group E,associate's degree,standard,none,100,100,100,99,37,97,100.000000
625,male,7,group D,some college,standard,completed,100,97,99,78,7,57,98.666667
458,female,28,group E,bachelor's degree,standard,none,100,100,100,69,28,13,100.000000
623,male,3,group A,some college,standard,completed,100,96,86,66,3,23,94.000000
451,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,53,group C,some college,free/reduced,none,22,39,33,47,53,28,31.333333
787,female,76,group B,some college,standard,none,19,38,32,29,76,89,29.666667
17,female,7,group B,some high school,free/reduced,none,18,32,28,43,7,19,26.000000
980,female,49,group B,high school,free/reduced,none,8,24,23,12,49,73,18.333333
59,female,27,group C,some high school,free/reduced,none,0,17,10,30,27,46,9.000000

In [232]:
#Sort descending by multiple columns
df_exams.sort_values(['math score', 'reading score'], ascending=False)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
149,male,14,group E,associate's degree,free/reduced,completed,100,100,93,51,14,92,97.666667
458,female,28,group E,bachelor's degree,standard,none,100,100,100,69,28,13,100.000000
916,male,83,group E,bachelor's degree,standard,completed,100,100,100,41,83,66,100.000000
962,female,37,group E,associate's degree,standard,none,100,100,100,99,37,97,100.000000
625,male,7,group D,some college,standard,completed,100,97,99,78,7,57,98.666667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,female,53,group C,some college,free/reduced,none,22,39,33,47,53,28,31.333333
787,female,76,group B,some college,standard,none,19,38,32,29,76,89,29.666667
17,female,7,group B,some high school,free/reduced,none,18,32,28,43,7,19,26.000000
980,female,49,group B,high school,free/reduced,none,8,24,23,12,49,73,18.333333
59,female,27,group C,some high school,free/reduced,none,0,17,10,30,27,46,9.000000

In [233]:
#Sort descending by multiple columns and update dataframe
#df_exams.sort_values(['math score', 'reading score'],ascending=False, inplace=True)

In [234]:
#sort descending with a key function
#You can sort the column as it is now, but we'll use the 'key' argument to ignore case of text
df_exams.sort_values('race/ethnicity',ascending=True, key=lambda col:col.str.lower())

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
778,female,21,group A,some college,standard,completed,72,79,82,63,21,52,77.666667
546,female,36,group A,some high school,standard,completed,92,100,97,37,36,93,96.333333
820,female,43,group A,some high school,standard,completed,85,90,92,76,43,69,89.000000
741,female,17,group A,associate's degree,free/reduced,none,37,57,56,91,17,3,50.000000
305,male,76,group A,some college,standard,none,69,67,69,1,76,46,68.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,male,38,group E,associate's degree,standard,completed,71,74,68,91,38,43,71.000000
293,female,26,group E,bachelor's degree,standard,none,65,73,75,44,26,16,71.000000
289,male,89,group E,some high school,standard,completed,77,76,77,3,89,8,76.666667
206,male,23,group E,bachelor's degree,standard,none,82,62,62,77,23,23,68.666667
499,male,28,group E,some college,standard,none,76,71,72,56,28,27,73.000000

###set_index() and sort_index() methods

In [235]:
import random

In [236]:
#Creating non repetitive values for the index
new_index = np.arange(0, 1000)

In [237]:
#shuffling the indexes
random.shuffle(new_index)

In [238]:
#create a new column with new index
df_exams['new_index'] = new_index
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average,new_index
0,female,58,group B,bachelor's degree,standard,none,72,72,74,87,58,54,72.666667,801
1,female,7,group C,some college,standard,completed,69,90,88,11,7,50,82.333333,873
2,female,68,group B,master's degree,standard,none,90,95,93,14,68,82,92.666667,593
3,male,28,group A,associate's degree,free/reduced,none,47,57,44,56,28,67,49.333333,334
4,male,47,group C,some college,standard,none,76,78,75,69,47,79,76.333333,865
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,76,group E,master's degree,standard,completed,88,99,95,94,76,54,94.000000,578
996,male,3,group C,high school,free/reduced,none,62,55,55,67,3,79,57.333333,559
997,female,6,group C,high school,free/reduced,completed,59,71,65,76,6,34,65.000000,94
998,female,95,group D,some college,standard,completed,68,78,77,78,95,24,74.333333,924
999,female,84,group D,some college,free/reduced,none,77,86,86,48,84,60,83.000000,281

In [239]:
#set new_index column as index
df_exams.set_index('new_index', inplace=True)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
801,female,58,group B,bachelor's degree,standard,none,72,72,74,87,58,54,72.666667
873,female,7,group C,some college,standard,completed,69,90,88,11,7,50,82.333333
593,female,68,group B,master's degree,standard,none,90,95,93,14,68,82,92.666667
334,male,28,group A,associate's degree,free/reduced,none,47,57,44,56,28,67,49.333333
865,male,47,group C,some college,standard,none,76,78,75,69,47,79,76.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
578,female,76,group E,master's degree,standard,completed,88,99,95,94,76,54,94.000000
559,male,3,group C,high school,free/reduced,none,62,55,55,67,3,79,57.333333
94,female,6,group C,high school,free/reduced,completed,59,71,65,76,6,34,65.000000
924,female,95,group D,some college,standard,completed,68,78,77,78,95,24,74.333333
281,female,84,group D,some college,free/reduced,none,77,86,86,48,84,60,83.000000

In [240]:
#sort dataframe by new index
df_exams.sort_index()

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
0,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000
1,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
2,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333

In [241]:
#sort descending by index
df_exams.sort_index(ascending=False, inplace=True)
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
2,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
1,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
0,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000

###Rename columns and index wit rename()

In [242]:
#Rename column and overwrite values of the dataframe 
df_exams.rename(columns={'gender':'Gender'})

,Gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
2,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
1,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
0,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000

In [243]:
#Rename multiple columns and update the dataframe with inplace argument
df_exams.rename(columns={'math score': 'MS', 'reading score': 'RS', 'writing score': 'WS'})

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,MS,RS,WS,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
2,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
1,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
0,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000

In [248]:
df_exams = df_exams.reset_index()

In [247]:
df_exams

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
C,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
B,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
A,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000

In [245]:
#rename index 0, 1 and 2 and update the dataframe
df_exams.rename(index={0:'A', 1:'B', 2:'C'},inplace=True)

In [246]:
#Show first 3 rows
df_exams.head(3)

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
new_index,,,,,,,,,,,,,
999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333

In [251]:
df_exams = df_exams.reset_index()
df_exams.head(3)

,level_0,index,new_index,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
0,0,0,999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
1,1,1,998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
2,2,2,997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333

In [257]:
df_exams_news = df_exams.copy()

In [258]:
df_exams_news

,level_0,index,new_index,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score_1,score_2,average
0,0,0,999,male,1,group C,some high school,free/reduced,none,69,71,65,58,1,57,68.333333
1,1,1,998,male,52,group E,some high school,standard,completed,87,84,76,6,52,60,82.333333
2,2,2,997,male,75,group D,high school,standard,none,76,73,68,39,75,19,72.333333
3,3,3,996,female,38,group D,some college,free/reduced,completed,52,59,65,81,38,69,58.666667
4,4,4,995,female,52,group D,master's degree,standard,completed,77,82,91,64,52,38,83.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,995,4,female,63,group E,some college,standard,none,100,92,97,49,63,10,96.333333
996,996,996,3,female,17,group B,some college,free/reduced,completed,53,66,73,54,17,50,64.000000
997,997,997,C,male,66,group C,high school,standard,completed,69,58,53,31,66,84,60.000000
998,998,998,B,female,55,group D,high school,standard,completed,88,99,100,90,55,57,95.666667
999,999,999,A,male,72,group C,some college,standard,completed,93,84,90,71,72,63,89.000000

In [268]:
#df_exams_news.drop(['new_index', 'level_0', 'index', 'score_1','score_2'], axis=1, inplace=True)
df_exams_news

,gender,test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,average
0,male,1,group C,some high school,free/reduced,none,69,71,65,58,68.333333
1,male,52,group E,some high school,standard,completed,87,84,76,6,82.333333
2,male,75,group D,high school,standard,none,76,73,68,39,72.333333
3,female,38,group D,some college,free/reduced,completed,52,59,65,81,58.666667
4,female,52,group D,master's degree,standard,completed,77,82,91,64,83.333333
...,...,...,...,...,...,...,...,...,...,...,...
995,female,63,group E,some college,standard,none,100,92,97,49,96.333333
996,female,17,group B,some college,free/reduced,completed,53,66,73,54,64.000000
997,male,66,group C,high school,standard,completed,69,58,53,31,60.000000
998,female,55,group D,high school,standard,completed,88,99,100,90,95.666667
999,male,72,group C,some college,standard,completed,93,84,90,71,89.000000