In [13]:
# import pandas
import pandas as pd
import numpy as np

In [3]:
# Optional: use the pd.set_option() to display all rows in a dataframe by default
pd.set_option('display.max_rows', 1000)

# Create a DataFrame

In [5]:
# read the "bestsellers with categories" csv file (Dataset on Amazon's Top 50 bestselling books from 2009 to 2019.)
df = pd.read_csv('bestsellers_with_categories.csv')
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [6]:
# get access to the shape attribute
df.shape

(550, 7)

In [9]:
# find the data types of each column
df.dtypes

Name            object
Author          object
User Rating    float64
Reviews          int64
Price            int64
Year             int64
Genre           object
dtype: object

# Disaplying a DataFrame

In [10]:
# show first 5 rows in a dataframe
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [12]:
# describe basic statistics of the dataframe (mean, std, min, max)
df.describe().round(2)

       User Rating   Reviews   Price     Year
count       550.00    550.00  550.00   550.00
mean          4.62  11953.28   13.10  2014.00
std           0.23  11731.13   10.84     3.17
min           3.30     37.00    0.00  2009.00
25%           4.50   4058.00    7.00  2011.00
50%           4.70   8580.00   11.00  2014.00
75%           4.80  17253.25   16.00  2017.00
max           4.90  87841.00  105.00  2019.00

# Add a new Column with an array

In [23]:
# Your task is to create a column named 'Critic Rating' that should have random integer numbers between 1 and 4

# 1. import numpy and create 550 random integer numbers between 1 and 4

# 2. add new 'Critic Rating' column to dataframe using the random numbers created


# Note the random numbers in this new 'Critic Rating' column will be different between your solution and mine, but we'll focus only on the code, in this section.
num_rand = np.random.randint(1, 5, size=550)
df['Critic Rating'] = num_rand

In [24]:
# show first 5 rows
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,4
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,3

# Basic Attributes, Methods and Functions

In [25]:
# get access to the columns attribute
df.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre',
       'Critic Rating'],
      dtype='object')

# Selecting Two or More Columns from a Dataframe

In [26]:
# move the new 'Critic Rating' column between the columns "User Rating" and "Reviews" Then update the dataframe

# Tip: Copy and paste the column names obtained with the columns attribute and then rearrange elements using [[]]
new_df = df[['User Rating', 'Critic Rating', 'Reviews']]

In [33]:
df_new = df.copy()
df_new.drop('Critic Rating', axis=1, inplace=True)
df_new.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction

In [37]:
#df_new.insert(3, 'Critic Rating', num_rand)
df_new.head()

,Name,Author,User Rating,Critic Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,4,17350,8,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,4,2052,22,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,1,18979,15,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,3,21424,6,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,3,7665,12,2019,Non Fiction

In [28]:
# show first 5 rows
new_df.head()

   User Rating  Critic Rating  Reviews
0          4.7              4    17350
1          4.6              4     2052
2          4.7              1    18979
3          4.7              3    21424
4          4.8              3     7665

# Operations on Dataframes

In [38]:
# create a column named "Average Rating" by using the following formula: Average Rating = (User Rating + Critic Rating)/2
df['Average Rating'] = (df['User Rating'] + df['Critic Rating'])/2

In [39]:
# use the round function to round the values of the dataframe to 1 decimal and update the dataframe
df = df.round(1)
df.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Critic Rating,Average Rating
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4,4.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,4,4.3
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1,2.8
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3,3.8
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,3,3.9

# Value Counts

In [42]:
# count elements in "Genre" column by category and return the relative frequency 
df['Genre'].value_counts(normalize=True)

Genre
Non Fiction    0.563636
Fiction        0.436364
Name: proportion, dtype: float64

# Rename Columns

In [47]:
# rename columns "User Rating," "Critic Rating" and "Average Rating" to "UR," "CR" and "AR" then update the dataframe with the inplace paraneter
df.rename(columns = {'User Rating': 'UR', 'Critic Rating': 'CR', 'Average Rating': 'AR'}, inplace=True)

In [46]:
# show first 5 rows
df.head()

,Name,Author,UR,Reviews,Price,Year,Genre,CR,AR
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350,8,2016,Non Fiction,4,4.4
1,11/22/63: A Novel,Stephen King,4.6,2052,22,2011,Fiction,4,4.3
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979,15,2018,Non Fiction,1,2.8
3,1984 (Signet Classics),George Orwell,4.7,21424,6,2017,Fiction,3,3.8
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665,12,2019,Non Fiction,3,3.9

In [48]:
# select only "Name", "Author", "UR", "CR", "AR" and "Year" columns and update dataframe
df = df[['Name', 'Author', 'UR', 'CR', 'AR', 'Year']]
df.head()

,Name,Author,UR,CR,AR,Year
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,4,4.4,2016
1,11/22/63: A Novel,Stephen King,4.6,4,4.3,2011
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,1,2.8,2018
3,1984 (Signet Classics),George Orwell,4.7,3,3.8,2017
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,3,3.9,2019

# Sort a dataframe

In [50]:
# sort the dataframe descending by "UR" and "CR"
df.sort_values(by=['UR', 'CR'], ascending=False).head()

,Name,Author,UR,CR,AR,Year
40,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,4,4.4,2017
41,"Brown Bear, Brown Bear, What Do You See?",Bill Martin Jr.,4.9,4,4.4,2019
82,Dog Man: A Tale of Two Kitties: From the Creat...,Dav Pilkey,4.9,4,4.4,2017
85,Dog Man: Fetch-22: From the Creator of Captain...,Dav Pilkey,4.9,4,4.4,2019
153,Harry Potter and the Chamber of Secrets: The I...,J.K. Rowling,4.9,4,4.4,2016